name: Build .NET Application and Capture Artifacts

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-upload-artifacts:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore NuGet packages for ScadaWeb
      run: dotnet restore
      working-directory: ./ScadaWeb/ScadaWeb

    - name: Build ScadaWeb - Release
      run: dotnet build --no-restore --configuration Release
      working-directory: ./ScadaWeb/ScadaWeb

    - name: Restore NuGet packages for OpenPlugins
      run: dotnet restore
      working-directory: ./ScadaWeb/OpenPlugins

    - name: Build OpenPlugins - Release
      run: dotnet build --no-restore --configuration Release
      working-directory: ./ScadaWeb/OpenPlugins

    - name: Publish ScadaWeb
      run: dotnet publish --no-restore --configuration Release --output ./publish
      working-directory: ./ScadaWeb/ScadaWeb

    # Upload the build outputs
    - name: Upload ScadaWeb Artefacts
      uses: actions/upload-artifact@v2
      with:
        name: scadaweb-release-artifacts
        path: |
          ./ScadaWeb/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWeb.exe
          ./ScadaWeb/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWeb.dll
          ./ScadaWeb/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWebCommon.dll
          ./ScadaWeb/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaCommon.dll

    - name: Upload PlgSchShapeComp JavaScript Files
      uses: actions/upload-artifact@v2
      with:
        name: plgschshapecomp-js-files
        path: ./ScadaWeb/OpenPlugins/PlgSchShapeComp/wwwroot/SchShapeComp/js/*.js


    # Les outputs de build ou répertoires
    - name: Upload PlgSchShapeComp Debug Artefact
      uses: actions/upload-artifact@v2
      with:
        name: plg-sch-shape-comp-debug
        path:  ./ScadaWeb/OpenPlugins/PlgSchShapeComp/bin/Release/net6.0/**

   
 # Répétez pour les autres outputs de build si nécessaire
  #  - name: Upload Build Output 3
   #   uses: actions/upload-artifact@v2
   #   with:
    #    name: build-output-3
    #    path: ./path/to/your/third/build/output/
