name: Build .NET Application and Capture Artifacts

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  setup-and-restore:
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    # Restaurez les packages NuGet pour tous les projets nécessaires ici
    - name: Restore NuGet packages for all projects
      run: |
        dotnet restore ScadaCommon/ScadaCommon.sln
        dotnet restore ScadaAgent/ScadaAgent/ScadaAgent.sln
        dotnet restore ScadaComm/ScadaComm/ScadaComm.sln
        dotnet restore ScadaServer/ScadaServer/ScadaServer.sln
        dotnet restore ScadaWeb/ScadaWeb/ScadaWeb.sln
        dotnet restore ScadaAdmin/ScadaAdmin/ScadaAdmin.sln
        dotnet restore ScadaReport/ScadaReport.sln
        dotnet restore ScadaComm/OpenDrivers/OpenDrivers.sln
        dotnet restore ScadaComm/OpenDrivers2/OpenDrivers2.sln
        dotnet restore ScadaServer/OpenModules/OpenModules.sln
        dotnet restore ScadaWeb/OpenPlugins/OpenPlugins.sln
        dotnet restore ScadaAdmin/OpenExtensions/OpenExtensions.sln

  build:
    needs: setup-and-restore
    runs-on: windows-latest
    strategy:
      matrix:
        project: [ScadaCommon, ScadaAgent, ScadaComm, ScadaServer, ScadaWeb, ScadaAdmin, ScadaReport, OpenDrivers, OpenDrivers2, OpenModules, OpenPlugins]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    # Construisez chaque projet dans l'ordre spécifié
    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaCommon/ScadaCommon.sln
      
    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaAgent/ScadaAgent/ScadaAgent.sln
      
    - name: Build${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaComm/ScadaComm/ScadaComm.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaServer/ScadaServer/ScadaServer.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaWeb/ScadaWeb/ScadaWeb.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaAdmin/ScadaAdmin/ScadaAdmin.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaReport/ScadaReport.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaComm/OpenDrivers/OpenDrivers.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaComm/OpenDrivers2/OpenDrivers2.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaServer/OpenModules/OpenModules.sln

    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore --configuration Release ScadaWeb/OpenPlugins/OpenPlugins.sln


  publish:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        
    - name: Publish ScadaCommon
      run: |
        dotnet publish ScadaCommon/ScadaCommon.sln --no-restore --configuration Release --output ./publish/ScadaCommon
        dotnet publish ScadaAgent/ScadaAgent/ScadaAgent.sln --no-restore --configuration Release --output ./publish/ScadaAgent
        dotnet publish ScadaComm/ScadaComm/ScadaComm.sln --no-restore --configuration Release --output ./publish/ScadaComm
        dotnet publish ScadaServer/ScadaServer/ScadaServer.sln --no-restore --configuration Release --output ./publish/ScadaServer
        dotnet publish ScadaWeb/ScadaWeb/ScadaWeb.sln --no-restore --configuration Release --output ./publish/ScadaWeb
        dotnet publish ScadaAdmin/ScadaAdmin/ScadaAdmin.sln --no-restore --configuration Release --output ./publish/ScadaAdmin
        dotnet publish ScadaReport/ScadaReport.sln --no-restore --configuration Release --output ./publish/ScadaReport
        dotnet publish ScadaComm/OpenDrivers/OpenDrivers.sln --no-restore --configuration Release --output ./publish/OpenDrivers
        dotnet publish ScadaComm/OpenDrivers2/OpenDrivers2.sln --no-restore --configuration Release --output ./publish/OpenDrivers2
        dotnet publish ScadaServer/OpenModules/OpenModules.sln --no-restore --configuration Release --output ./publish/OpenModules
        dotnet publish ScadaWeb/OpenPlugins/OpenPlugins.sln --no-restore --configuration Release --output ./publish/OpenPlugins

   # - name: Publish OpenExtensions
    #  run: dotnet publish ScadaAdmin/OpenExtensions/OpenExtensions.sln --no-restore --configuration Release --output ./publish/OpenExtensions

  upload-artifacts:
    needs: publish
    runs-on: windows-latest
    steps:
    - name: Upload ScadaWebV6 DLL
      uses: actions/upload-artifact@v2
      with:
        name: scadaweb-artifact
        path: |
          ./publish/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWeb.exe
          ./publish/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWeb.dll
          ./publish/ScadaWeb/ScadaWeb/bin/Release/net6.0/ScadaWebCommon.dll
          ./publish/ScadaWeb/OpenPlugins/PlgSchShapeComp/bin/**/PlgSchShapeComp.dll
          ./publish/ScadaWeb/OpenPlugins/PlgSchShapeComp/wwwroot/SchShapeComp/**/*.js
          
